-- H_SkillList.lua	v1.50.1
-- Kimi-only skill list and skill info
-- Generated by Kimi AI Config (GUI)

-- Kimi Skills

S_ILLUSION_OF_CLAWS	= 8009
S_WARM_DEF = 8006
S_CHAOTIC_HEAL = 8014
S_BODY_DOUBLE = 8022
S_ILLUSION_OF_BREATH = 8024
S_ILLUSION_CRUSHER = 8031
S_ILLUSION_OF_LIGHT = 8034
S_MASTER_SWAP = 8005 -- TODO: replace with actual ID

--SkillList[homuntype][skillid] = level

SkillList={}

SkillList[AGILE] = {}
SkillList[AGILE][S_ILLUSION_OF_CLAWS] = 5
SkillList[AGILE][S_ILLUSION_CRUSHER] = 5
SkillList[AGILE][S_CHAOTIC_HEAL] = 5
SkillList[AGILE][S_WARM_DEF] = 5
SkillList[AGILE][S_BODY_DOUBLE] = 5
SkillList[AGILE][S_MASTER_SWAP] = 0

SkillList[OCCULT] = {}
SkillList[OCCULT][S_ILLUSION_OF_LIGHT] = 10
SkillList[OCCULT][S_ILLUSION_OF_BREATH] = 10
SkillList[OCCULT][S_CHAOTIC_HEAL] = 5
SkillList[OCCULT][S_WARM_DEF] = 5
SkillList[OCCULT][S_BODY_DOUBLE] = 5
SkillList[OCCULT][S_MASTER_SWAP] = 0

SkillList[RAGING] = {}
SkillList[RAGING][S_ILLUSION_OF_CLAWS] = 5
SkillList[RAGING][S_ILLUSION_CRUSHER] = 5
SkillList[RAGING][S_CHAOTIC_HEAL] = 5
SkillList[RAGING][S_WARM_DEF] = 5
SkillList[RAGING][S_BODY_DOUBLE] = 5
SkillList[RAGING][S_MASTER_SWAP] = 0

SkillList[WARD] = {}
SkillList[WARD][S_ILLUSION_OF_CLAWS] = 5
SkillList[WARD][S_ILLUSION_CRUSHER] = 5
SkillList[WARD][S_CHAOTIC_HEAL] = 5
SkillList[WARD][S_WARM_DEF] = 5
SkillList[WARD][S_BODY_DOUBLE] = 5
SkillList[WARD][S_MASTER_SWAP] = 0

SkillInfo={}
SkillInfo[0] = {"No Skill",{0,0,0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0,0,0}}

SkillInfo[S_ILLUSION_OF_CLAWS] = {
  "Illusion of Claws",
  {1,1,1,1,1},
  {5,10,15,20,25},
  {100,100,100,100,100},
  {0,0,0,0,0},
  {0,0,0,0,0},
  1,
  {0,0,0,0,0},
  {0,0,0,0,0},
}

SkillInfo[S_ILLUSION_CRUSHER] = {
  "Illusion of Crusher",
  {1,1,1,1,1},
  {50,75,100,125,150},
  {0,0,0,0,0},
  {0,0,0,0,0},
  {0,0,0,0,0},
  1,
  {0,0,0,0,0},
  {0,0,0,0,0},
}

SkillInfo[S_WARM_DEF] = {
  "Warm Defense",
  {0,0,0,0,0},
  {20,25,30,35,40},
  {0,0,0,0,0},
  {0,0,0,0,0},
  {4100,4100,4100,4100,4100},
  0,
  {2000,4000,6000,8000,10000},
  {8350,8350,8350,8350,8350},
}

SkillInfo[S_CHAOTIC_HEAL] = {
  "Chaotic Heal",
  {0,0,0,0,0},
  {50,50,50,50,50},
  {0,0,0,0,0},
  {0,0,0,0,0},
  {0,0,0,0,0},
  0,
  {0,0,0,0,0},
  {0,0,0,0,0}
}

SkillInfo[S_BODY_DOUBLE] = {
  "Body Double",
  {0,0,0,0,0},
  {20,40,60,80,100},
  {0,0,0,0,0},
  {0,0,0,0,0},
  {0,0,0,0,0},
  0,
  {10000,20000,30000,40000,50000},
  {17500,17500,23000,30000,25000}
}

SkillInfo[S_ILLUSION_OF_BREATH] = {
  "Illusion of Breath",
  {7,7,7,7,7,7,7,7,7,7},
  {25,30,35,40,45,50,55,60,65,70},
  {0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0},
  1,
  {0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0}
}

SkillInfo[S_ILLUSION_OF_LIGHT] = {
  "Illusion of Light",
  {7,7,7,7,7,7,7,7,7,7},
  {25,30,35,40,45,50,55,60,65,70},
  {0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0},
  1,
  {0,0,0,0,0,0,0,0,0,0},
  {0,0,0,0,0,0,0,0,0,0}
}

SkillInfo[S_MASTER_SWAP] = {
  "Master Swap (placeholder)",
  {0,0,0,0,0},
  {0,0,0,0,0},
  {0,0,0,0,0},
  {0,0,0,0,0},
  {0,0,0,0,0},
  0,
  {0,0,0,0,0},
  {0,0,0,0,0}
}

SkillAOEInfo={}
SkillAOEInfo[0] = {{0,0,0,0,0},0}
SkillAOEInfo[S_ILLUSION_OF_LIGHT] = {
  {3,3,3,3,3,3,3,3,3,3},
  0
}

