// SkillList.cs
//
// Adds generation support for H_SkillList.lua (Kimi-only)
// Generates default skill mappings for all four Kimi types and writes SkillInfo.
// Master Swap scaffolding included (placeholder ID).

using System;
using System.IO;
using System.Text;

namespace AzzyAIConfig
{
    public static class SkillList
    {
        // Master Swap skill ID for Echoes of Morroc
        // This value controls "S_MASTER_SWAP" in H_SkillList.lua
        public static int MasterSwapSkillId { get; set; } // Confirmed for Echoes of Morroc

        // Default levels per Kimi type for Master Swap (0 disables)
        public static int MasterSwapLevelWard { get; set; }
        public static int MasterSwapLevelOccult { get; set; }
        public static int MasterSwapLevelAgile { get; set; }
        public static int MasterSwapLevelRaging { get; set; }

        static SkillList()
        {
            MasterSwapSkillId = 8005;
            MasterSwapLevelWard = 0;
            MasterSwapLevelOccult = 0;
            MasterSwapLevelAgile = 0;
            MasterSwapLevelRaging = 0;
        }

        public static void Save(string fileName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- H_SkillList.lua\tv1.50.1");
            sb.AppendLine("-- Kimi-only skill list and skill info");
            sb.AppendLine("-- Generated by Kimi AI Config (GUI)\n");
            sb.AppendLine("-- Kimi Skills\n");
            sb.AppendLine("S_ILLUSION_OF_CLAWS\t= 8009");
            sb.AppendLine("S_WARM_DEF = 8006");
            sb.AppendLine("S_CHAOTIC_HEAL = 8014");
            sb.AppendLine("S_BODY_DOUBLE = 8022");
            sb.AppendLine("S_ILLUSION_OF_BREATH = 8024");
            sb.AppendLine("S_ILLUSION_CRUSHER = 8031");
            sb.AppendLine("S_ILLUSION_OF_LIGHT = 8034");
            sb.AppendLine("S_MASTER_SWAP = " + MasterSwapSkillId + " -- TODO: replace with actual ID\n");

            sb.AppendLine("--SkillList[homuntype][skillid] = level\n");
            sb.AppendLine("SkillList={}\n");

            // Agile
            sb.AppendLine("SkillList[AGILE] = {}");
            sb.AppendLine("SkillList[AGILE][S_ILLUSION_OF_CLAWS] = 5");
            sb.AppendLine("SkillList[AGILE][S_ILLUSION_CRUSHER] = 5");
            sb.AppendLine("SkillList[AGILE][S_CHAOTIC_HEAL] = 5");
            sb.AppendLine("SkillList[AGILE][S_WARM_DEF] = 5");
            sb.AppendLine("SkillList[AGILE][S_BODY_DOUBLE] = 5");
            sb.AppendLine("SkillList[AGILE][S_MASTER_SWAP] = " + MasterSwapLevelAgile + "\n");

            // Occult
            sb.AppendLine("SkillList[OCCULT] = {}");
            sb.AppendLine("SkillList[OCCULT][S_ILLUSION_OF_LIGHT] = 10");
            sb.AppendLine("SkillList[OCCULT][S_ILLUSION_OF_BREATH] = 10");
            sb.AppendLine("SkillList[OCCULT][S_CHAOTIC_HEAL] = 5");
            sb.AppendLine("SkillList[OCCULT][S_WARM_DEF] = 5");
            sb.AppendLine("SkillList[OCCULT][S_BODY_DOUBLE] = 5");
            sb.AppendLine("SkillList[OCCULT][S_MASTER_SWAP] = " + MasterSwapLevelOccult + "\n");

            // Raging
            sb.AppendLine("SkillList[RAGING] = {}");
            sb.AppendLine("SkillList[RAGING][S_ILLUSION_OF_CLAWS] = 5");
            sb.AppendLine("SkillList[RAGING][S_ILLUSION_CRUSHER] = 5");
            sb.AppendLine("SkillList[RAGING][S_CHAOTIC_HEAL] = 5");
            sb.AppendLine("SkillList[RAGING][S_WARM_DEF] = 5");
            sb.AppendLine("SkillList[RAGING][S_BODY_DOUBLE] = 5");
            sb.AppendLine("SkillList[RAGING][S_MASTER_SWAP] = " + MasterSwapLevelRaging + "\n");

            // Ward
            sb.AppendLine("SkillList[WARD] = {}");
            sb.AppendLine("SkillList[WARD][S_ILLUSION_OF_CLAWS] = 5");
            sb.AppendLine("SkillList[WARD][S_ILLUSION_CRUSHER] = 5");
            sb.AppendLine("SkillList[WARD][S_CHAOTIC_HEAL] = 5");
            sb.AppendLine("SkillList[WARD][S_WARM_DEF] = 5");
            sb.AppendLine("SkillList[WARD][S_BODY_DOUBLE] = 5");
            sb.AppendLine("SkillList[WARD][S_MASTER_SWAP] = " + MasterSwapLevelWard + "\n");

            // SkillInfo tables (match existing values; Master Swap minimal placeholder)
            sb.AppendLine("SkillInfo={}");
            sb.AppendLine("SkillInfo[0] = {\"No Skill\",{0,0,0,0,0,0,0,0,0,0},{0,0,0,0,0,0,0,0,0,0}}\n");
            sb.AppendLine("SkillInfo[S_ILLUSION_OF_CLAWS] = {\n  \"Illusion of Claws\",\n  {1,1,1,1,1},\n  {5,10,15,20,25},\n  {100,100,100,100,100},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  1,\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n}\n");
            sb.AppendLine("SkillInfo[S_ILLUSION_CRUSHER] = {\n  \"Illusion of Crusher\",\n  {1,1,1,1,1},\n  {50,75,100,125,150},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  1,\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n}\n");
            sb.AppendLine("SkillInfo[S_WARM_DEF] = {\n  \"Warm Defense\",\n  {0,0,0,0,0},\n  {20,25,30,35,40},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  {4100,4100,4100,4100,4100},\n  0,\n  {2000,4000,6000,8000,10000},\n  {8350,8350,8350,8350,8350},\n}\n");
            sb.AppendLine("SkillInfo[S_CHAOTIC_HEAL] = {\n  \"Chaotic Heal\",\n  {0,0,0,0,0},\n  {50,50,50,50,50},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  0,\n  {0,0,0,0,0},\n  {0,0,0,0,0}\n}\n");
            sb.AppendLine("SkillInfo[S_BODY_DOUBLE] = {\n  \"Body Double\",\n  {0,0,0,0,0},\n  {20,40,60,80,100},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  0,\n  {10000,20000,30000,40000,50000},\n  {17500,17500,23000,30000,25000}\n}\n");
            sb.AppendLine("SkillInfo[S_ILLUSION_OF_BREATH] = {\n  \"Illusion of Breath\",\n  {7,7,7,7,7,7,7,7,7,7},\n  {25,30,35,40,45,50,55,60,65,70},\n  {0,0,0,0,0,0,0,0,0,0},\n  {0,0,0,0,0,0,0,0,0,0},\n  {0,0,0,0,0,0,0,0,0,0},\n  1,\n  {0,0,0,0,0,0,0,0,0,0},\n  {0,0,0,0,0,0,0,0,0,0}\n}\n");
            sb.AppendLine("SkillInfo[S_ILLUSION_OF_LIGHT] = {\n  \"Illusion of Light\",\n  {7,7,7,7,7,7,7,7,7,7},\n  {25,30,35,40,45,50,55,60,65,70},\n  {0,0,0,0,0,0,0,0,0,0},\n  {0,0,0,0,0,0,0,0,0,0},\n  {0,0,0,0,0,0,0,0,0,0},\n  1,\n  {0,0,0,0,0,0,0,0,0,0},\n  {0,0,0,0,0,0,0,0,0,0}\n}\n");
            sb.AppendLine("SkillInfo[S_MASTER_SWAP] = {\n  \"Master Swap (placeholder)\",\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  {0,0,0,0,0},\n  0,\n  {0,0,0,0,0},\n  {0,0,0,0,0}\n}\n");

            // SkillAOEInfo (same as existing)
            sb.AppendLine("SkillAOEInfo={}");
            sb.AppendLine("SkillAOEInfo[0] = {{0,0,0,0,0},0}");
            sb.AppendLine("SkillAOEInfo[S_ILLUSION_OF_LIGHT] = {\n  {3,3,3,3,3,3,3,3,3,3},\n  0\n}\n");

            File.WriteAllText(fileName, sb.ToString());
        }
    }
}
